// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT = 'LOGOUT';
export const PROFILE_PICTURE_UPLOADED = 'PROFILE_PICTURE_UPLOADED';
export const PROFILE_PICTURE_REMOVED = 'PROFILE_PICTURE_REMOVED';
export const NAME_UPDATED = 'NAME_UPDATED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
export const ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED';
export const ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED';

// PROFILE
export const ALL_PROFILES_LOADED = 'ALL_PROFILES_LOADED';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const EXPERIENCE_ADDED = 'EXPERIENCE_ADDED';
export const EXPERIENCE_REMOVED = 'EXPERIENCE_REMOVED';
export const EDUCATION_ADDED = 'EDUCATION_ADDED';
export const EDUCATION_REMOVED = 'EDUCATION_REMOVED';
export const PROFILE_DELETED = 'PROFILE_DELETED';
export const USER_DELETED = 'USER_DELETED';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';

// REQUEST
export const ALL_REQUESTS_LOADED_FOR_UNIVERSITY =
  'ALL_REQUESTS_LOADED_FOR_UNIVERSITY';
export const ALL_REQUESTS_LOADED_FOR_USER = 'ALL_REQUESTS_LOADED_FOR_USER';
export const ALL_REQUESTS_LOADED_FOR_HEC = 'ALL_REQUESTS_LOADED_FOR_HEC';
export const REQUEST_LOADED = 'REQUEST_LOADED';
export const REQUEST_CREATED = 'REQUEST_CREATED';
export const REQUEST_FORWARDED = 'REQUEST_FORWARDED';
export const REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const SET_REQUEST_LOADING = 'SET_REQUEST_LOADING';

// COMPLAINT
export const ALL_COMPLAINTS_LOADED_FOR_UNIVERSITY =
  'ALL_COMPLAINTS_LOADED_FOR_UNIVERSITY';
export const ALL_COMPLAINTS_LOADED_FOR_USER = 'ALL_COMPLAINTS_LOADED_FOR_USER';
export const ALL_COMPLAINTS_LOADED_FOR_HEC = 'ALL_COMPLAINTS_LOADED_FOR_HEC';
export const COMPLAINT_LOADED = 'COMPLAINT_LOADED';
export const COMPLAINT_CREATED = 'COMPLAINT_CREATED';
export const COMPLAINT_FORWARDED = 'COMPLAINT_FORWARDED';
export const COMPLAINT_CONSIDERED = 'COMPLAINT_CONSIDERED';
export const COMPLAINT_NOT_CONSIDERED = 'COMPLAINT_NOT_CONSIDERED';
export const COMPLAINT_ERROR = 'COMPLAINT_ERROR';
export const SET_COMPLAINT_LOADING = 'SET_COMPLAINT_LOADING';

// UNIVERSITY
export const ALL_UNIVERSITIES_LOADED = 'ALL_UNIVERSITIES_LOADED';
export const UNIVERSITY_REMOVED = 'UNIVERSITY_REMOVED';
export const UNIVERSITY_ERROR = 'UNIVERSITY_ERROR';
export const SET_UNIVERSTITY_LOADING = 'SET_UNIVERSTITY_LOADING';

// STUDENT
export const ALL_STUDENTS_LOADED = 'ALL_STUDENTS_LOADED';
export const STUDENT_REMOVED = 'STUDENT_REMOVED';
export const STUDENT_ERROR = 'STUDENT_ERROR';

// BLOCKCHAIN
export const ALL_BLOCKCHAINS_LOADED = 'ALL_BLOCKCHAINS_LOADED';
export const ALL_TRANSACTIONS_LOADED = 'ALL_TRANSACTIONS_LOADED';
export const ALL_TRANSACTIONS_LOADED_FOR_USER =
  'ALL_TRANSACTIONS_LOADED_FOR_USER';
export const TRANSACTION_CREATED = 'TRANSACTION_CREATED';
export const ALL_TRANSACTIONS_VERIFIED = 'ALL_TRANSACTIONS_VERIFIED';
export const BLOCKCHAIN_FIXED = 'BLOCKCHAIN_FIXED';
export const BLOCKCHAIN_ERROR = 'BLOCKCHAIN_ERROR';
export const SET_BLOCKCHAIN_LOADING = 'SET_BLOCKCHAIN_LOADING';

// SCRAPPER
export const ALL_SCRAPPED_DATA_LOADED = 'ALL_SCRAPED_DATA_LOADED';
export const SCRAPPED_ERROR = 'SCRAPPED_ERROR';

// POST
export const ALL_POSTS_LOADED = 'ALL_POSTS_LOADED';
export const POST_LOADED = 'POST_LOADED';
export const POST_ADDED = 'POST_ADDED';
export const POST_LIKED = 'POST_LIKED';
export const POST_UNLIKED = 'POST_UNLIKED';
export const COMMENT_ADDED_POST = 'COMMENT_ADDED_POST';
export const COMMENT_REMOVED_POST = 'COMMENT_REMOVED_POST';
export const POST_REMOVED = 'POST_REMOVED';
export const POST_ERROR = 'POST_ERROR';
export const SET_POST_LOADING = 'SET_POST_LOADING';

// GROUP
export const ALL_GROUPS_LOADED = 'ALL_GROUPS_LOADED';
export const GROUP_LOADED = 'GROUP_LOADED';
export const GROUP_CREATED = 'GROUP_CREATED';
export const GROUP_UPDATED = 'GROUP_UPDATED';
export const GROUP_DELETED = 'GROUP_DELETED';
export const GROUP_ERROR = 'GROUP_ERROR';
export const SET_GROUP_LOADING = 'SET_GROUP_LOADING';

// DATA VISUALIZATION
export const ALL_DV_DATA_LOADED_UNIVERSITY = 'ALL_DV_DATA_LOADED_UNIVERSITY';
export const ALL_DV_DATA_LOADED_YEAR = 'ALL_DV_DATA_LOADED_YEAR';
export const DV_ERROR = 'DV_ERROR';
export const SET_DV_LOADING = 'SET_DV_LOADING';
