// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT = 'LOGOUT';
export const PROFILE_PICTURE_UPLOADED = 'PROFILE_PICTURE_UPLOADED';
export const PROFILE_PICTURE_REMOVED = 'PROFILE_PICTURE_REMOVED';
export const NAME_UPDATED = 'NAME_UPDATED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';

// PROFILE
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const EXPERIENCE_ADDED = 'EXPERIENCE_ADDED';
export const EXPERIENCE_REMOVED = 'EXPERIENCE_REMOVED';
export const EDUCATION_ADDED = 'EDUCATION_ADDED';
export const EDUCATION_REMOVED = 'EDUCATION_REMOVED';
export const PROFILE_DELETED = 'PROFILE_DELETED';
export const USER_DELETED = 'USER_DELETED';

// REQUEST
export const ALL_REQUESTS_LOADED_FOR_UNIVERSITY =
  'ALL_REQUESTS_LOADED_FOR_UNIVERSITY';
export const ALL_REQUESTS_LOADED_FOR_USER = 'ALL_REQUESTS_LOADED_FOR_USER';
export const ALL_REQUESTS_LOADED_FOR_HEC = 'ALL_REQUESTS_LOADED_FOR_HEC';
export const REQUEST_LOADED = 'REQUEST_LOADED';
export const REQUEST_CREATED = 'REQUEST_CREATED';
export const REQUEST_FORWARDED = 'REQUEST_FORWARDED';
export const REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';
export const REQUEST_ERROR = 'REQUEST_ERROR';

// COMPLAINT
export const ALL_COMPLAINTS_LOADED_FOR_UNIVERSITY =
  'ALL_COMPLAINTS_LOADED_FOR_UNIVERSITY';
export const ALL_COMPLAINTS_LOADED_FOR_USER = 'ALL_COMPLAINTS_LOADED_FOR_USER';
export const ALL_COMPLAINTS_LOADED_FOR_HEC = 'ALL_COMPLAINTS_LOADED_FOR_HEC';
export const COMPLAINT_LOADED = 'COMPLAINT_LOADED';
export const COMPLAINT_CREATED = 'COMPLAINT_CREATED';
export const COMPLAINT_FORWARDED = 'COMPLAINT_FORWARDED';
export const COMPLAINT_CONSIDERED = 'COMPLAINT_CONSIDERED';
export const COMPLAINT_NOT_CONSIDERED = 'COMPLAINT_NOT_CONSIDERED';
export const COMPLAINT_ERROR = 'COMPLAINT_ERROR';

// UNIVERSITY
export const ALL_UNIVERSITIES_LOADED = 'ALL_UNIVERSITIES_LOADED';
export const UNIVERSITY_REMOVED = 'UNIVERSITY_REMOVED';
export const UNIVERSITY_ERROR = 'UNIVERSITY_ERROR';

// STUDENT
export const ALL_STUDENTS_LOADED = 'ALL_STUDENTS_LOADED';
export const STUDENT_REMOVED = 'STUDENT_REMOVED';
export const STUDENT_ERROR = 'STUDENT_ERROR';

// BLOCKCHAIN
export const ALL_BLOCKCHAINS_LOADED = 'ALL_BLOCKCHAINS_LOADED';
export const ALL_TRANSACTIONS_LOADED = 'ALL_TRANSACTIONS_LOADED';
export const ALL_TRANSACTIONS_LOADED_FOR_USER =
  'ALL_TRANSACTIONS_LOADED_FOR_USER';
export const TRANSACTION_CREATED = 'TRANSACTION_CREATED';
export const ALL_TRANSACTIONS_VERIFIED = 'ALL_TRANSACTIONS_VERIFIED';
export const BLOCKCHAIN_FIXED = 'BLOCKCHAIN_FIXED';
export const BLOCKCHAIN_ERROR = 'BLOCKCHAIN_ERROR';

// SCRAPPER
export const ALL_SCRAPPED_DATA_LOADED = 'ALL_SCRAPED_DATA_LOADED';
export const SCRAPPED_ERROR = 'SCRAPPED_ERROR';
