// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT = 'LOGOUT';
export const PROFILE_PICTURE_UPLOADED = 'PROFILE_PICTURE_UPLOADED';
export const PROFILE_PICTURE_REMOVED = 'PROFILE_PICTURE_REMOVED';
export const NAME_UPDATED = 'NAME_UPDATED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';

// PROFILE
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const EXPERIENCE_ADDED = 'EXPERIENCE_ADDED';
export const EXPERIENCE_REMOVED = 'EXPERIENCE_REMOVED';
export const EDUCATION_ADDED = 'EDUCATION_ADDED';
export const EDUCATION_REMOVED = 'EDUCATION_REMOVED';
export const PROFILE_DELETED = 'PROFILE_DELETED';
export const USER_DELETED = 'USER_DELETED';

// REQUEST
export const ALL_REQUESTS_LOADED_FOR_USER = 'ALL_REQUESTS_LOADED_FOR_USER';
export const REQUEST_ERROR = 'REQUEST_ERROR';
